[package]
name = "daan_compile"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
papier = { version = "0.1.0", path = "../base" }
render_staal = { version = "0.1.0", path = "../render_staal" }